const tagline = [
  'Protecting Your Tomorrow, Today.',
  3000,
  'Your Shield of Financial Security.',
  3000,
  "Life's Uncertainties, Our Certainties.",
  3000,
  'Insuring Your Dreams, One Policy at a Time.',
  3000,
  "Guarding Your Loved Ones' Future.",
  3000,
  "Empowering Your Family's Financial Future.",
  3000,
  'Life Insurance Solutions Tailored to You.',
  3000,
  'Your Partner in Ensuring Peace of Mind.',
  3000,
  'Life Insurance Made Simple, Secure, and Smart.',
  3000,
  'Safeguarding Your Legacy, Today and Tomorrow.',
  3000,
  'Building a Financial Foundation for Generations.',
  3000,
  'Committed to Protecting Indian Families.',
  3000,
  'Secure Today, Insure Tomorrow.',
  3000,
  "Life Happens. We're Here to Ensure It's Secure.",
  3000,
  'Your Life, Your Legacy, Our Assurance.',
  3000,
  'Planning Ahead, Living in Confidence.',
  3000,
  "Life Insurance: Your Family's Lifeline.",
  3000,
  'Your Trust, Our Coverage.',
  3000,
];
export default tagline;
